# safelist
branches:
  only:
  - testing
before_install:
- sudo apt-get update
- sudo apt-get upgrade -y
install:
- sudo apt-get install git clang-3.6 clang-3.6-dev llvm-3.6 llvm-3.6-dev libboost-dev libboost-filesystem-dev libboost-date-time-dev libboost-serialization-dev libboost-iostreams-dev libboost-program-options-dev libboost-random-dev libboost-regex-dev libboost-system-dev libgmp-dev autoconf automake libtool libexpat-dev libz-dev libncurses-dev libreadline-dev libedit-dev sbcl --no-install-recommends -y
env:
- PJOBS=2
script:
- git checkout testing
- make clean
- make
